vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        #    products:
        #        uri_prefix: /images/products
        #        upload_destination: '%kernel.project_dir%/public/images/products'
        #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        marques:
            uri_prefix: /images/marques
            upload_destination: "%kernel.project_dir%/public/images/marques"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_remove: true
            delete_on_update: true

        models:
            uri_prefix: /images/models
            upload_destination: "%kernel.project_dir%/public/images/models"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_remove: true
            delete_on_update: true
